apiVersion: apps/v1
kind: Deployment
metadata:
  name: coco-fake-kbs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coco-fake-kbs
  template:
    metadata:
      labels:
        app: coco-fake-kbs
    spec:
      containers:
        - name: coco-fake-kbs
          image: ghcr.io/katexochen/coco-fake-kbs
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: coco-fake-kbs
spec:
  selector:
    app: coco-fake-kbs
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
